---
sudo: required
env:
  - base_image: 5003/systemd
  - base_image: ubuntu:14.04
  - base_image: ubuntu:16.04
  - base_image: ubuntu:16.10
  - base_image: ubuntu:17.04
  - base_image: debian:7
  - base_image: debian:8

services: docker
script:
  - roles_path=/ci/
  - container_id=$(mktemp)
  - >
     sudo docker run --detach --privileged
     --volume="${PWD}":${roles_path}:ro
     --volume=/sys/fs/cgroup/:/sys/fs/cgroup/:ro
     ${base_image} > "${container_id}"
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     make --directory $roles_path install-ansible
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     PARAM="--verbose --limit master --tags common:setup" make --directory $roles_path play local || :
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     PARAM="--verbose --limit master --tags common:setup,docker" make --directory $roles_path play local || :
  - >
     sudo docker exec "$(cat ${container_id})"
     env PARAM="--limit master --tags common:setup" make --directory $roles_path play local
     | grep --quiet 'unreachable=0.*failed=0'
     && (echo 'Task idempotent state: PASSED' && exit 0)
     || (echo 'Task idempotent state: FAILED' && exit 1)
  - 'sudo docker stop "$(cat ${container_id})"'