---
sudo: required
env:
  - base_image: 5003/centos-ansible-ci:2.1.x
    roles_path: /ci/
services: docker
script:
  - container_id=$(mktemp)
  - >
     sudo docker run --detach --privileged
     --volume="${PWD}":${roles_path}:ro
     --volume=/sys/fs/cgroup/:/sys/fs/cgroup/:ro
     ${base_image} > "${container_id}"
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     make --directory $roles_path install-ansible
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     PARAM="--limit master --tags common:setup" make --directory $roles_path play local
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     PARAM="--limit master --tags common:setup" make --directory $roles_path play local
  - >
     sudo docker exec "$(cat ${container_id})"
     PARAM="--limit master --tags common:setup" make --directory $roles_path play local
     | grep --quiet 'unreachable=0.*failed=0'
     && (echo 'Task idempotent state: PASSED' && exit 0)
     || (echo 'Task idempotent state: FAILED' && exit 1)
  - 'sudo docker stop "$(cat ${container_id})"'