---
sudo: required
env:
  - base_image: geerlingguy/docker-centos7-ansible
    run_opts: /usr/sbin/init
  - base_image: geerlingguy/docker-ubuntu1404-ansible
    run_opts: /sbin/init
  - base_image: geerlingguy/docker-ubuntu1604-ansible
    run_opts: /sbin/init
  - base_image: geerlingguy/docker-debian8-ansible
    run_opts: /sbin/init

services: docker
script:
  - roles_path=/ci/
  - container_id=$(mktemp)
  - >
     sudo docker run --detach --privileged
     --volume="${PWD}":${roles_path}:ro
     --volume=/sys/fs/cgroup/:/sys/fs/cgroup/:ro
     ${base_image} ${run_opts} > "${container_id}"
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     yum -y install make wget || :
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     make --directory $roles_path install-ansible
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     PARAM="--verbose --limit master --tags common:setup" make --directory $roles_path play local || :
  - >
     sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm
     PARAM="--verbose --limit master --tags common:setup,docker" make --directory $roles_path play local || :
  - >
     sudo docker exec "$(cat ${container_id})"
     env PARAM="--limit master --tags common:setup" make --directory $roles_path play local
     | grep --quiet 'unreachable=0.*failed=0'
     && (echo 'Task idempotent state: PASSED' && exit 0)
     || (echo 'Task idempotent state: FAILED' && exit 1)
  - 'sudo docker stop "$(cat ${container_id})"'